#!/bin/sh
if [ $1 = "get_data" ]
then
  python3 $@
elif [ $1 = "calc_indicators" ]
then
  python3 $@
else
  echo "Type stt get_data --help, stt calc_indicators --help to get help for the separate tools"
fi
