# Generated by Django 3.1.2 on 2020-11-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginRecord',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
