# Generated by Django 3.1.2 on 2020-10-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='datetime')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('success', models.BooleanField(verbose_name='success')),
                ('pass_attempted', models.CharField(max_length=256, verbose_name='pass_attempted')),
            ],
            options={
                'db_table': 'login_record',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50, verbose_name='username'),
        ),
    ]
