# Generated by Django 3.1.2 on 2020-10-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('open', models.FloatField(verbose_name='open')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('close', models.FloatField(verbose_name='close')),
                ('volume', models.FloatField(verbose_name='volume')),
                ('source', models.CharField(max_length=200, verbose_name='source')),
            ],
        ),
    ]
