# Generated by Django 3.1.2 on 2020-10-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_stocks', '0002_auto_20201014_1530'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stocks',
            table='historical_stock_info',
        ),
    ]
