# Generated by Django 3.1.2 on 2020-10-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_stocks', '0003_auto_20201014_1542'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stocks',
            table='historical_stock_data',
        ),
    ]
