# Generated by Django 3.1.2 on 2020-10-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_stocks', '0004_auto_20201014_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date_pulled')),
                ('symbol', models.CharField(max_length=200, verbose_name='symbol')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('exchange', models.CharField(max_length=200, verbose_name='exchange')),
                ('currency', models.CharField(max_length=200, verbose_name='currency')),
                ('region', models.CharField(max_length=200, verbose_name='region')),
                ('source', models.CharField(max_length=200, verbose_name='source')),
                ('type', models.CharField(max_length=200, verbose_name='type')),
            ],
            options={
                'db_table': 'symbols',
            },
        ),
    ]
