# Generated by Django 3.1.2 on 2020-10-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_stocks', '0005_symbols'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('symbol', models.CharField(max_length=10, verbose_name='symbol')),
                ('open', models.FloatField(verbose_name='open')),
                ('high', models.FloatField(verbose_name='high')),
                ('low', models.FloatField(verbose_name='low')),
                ('close', models.FloatField(verbose_name='close')),
                ('volume', models.FloatField(verbose_name='volume')),
                ('source', models.CharField(max_length=200, verbose_name='source')),
            ],
            options={
                'db_table': 'historical_stock_data',
            },
        ),
        migrations.RenameModel(
            old_name='Symbols',
            new_name='Symbol',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
